// built using utils/parse_aws_services.php and markup from the AWS console and the main AWS pricing page
var all_services = [
    [
        "api_gateway",
        "API Gateway",
        "https:\/\/console.aws.amazon.com\/apigateway\/home",
        "https:\/\/aws.amazon.com\/api-gateway\/pricing\/"
    ],
    [
        "aws_greengrass",
        "AWS Greengrass",
        "https:\/\/console.aws.amazon.com\/greengrass\/home",
        "https:\/\/aws.amazon.com\/greengrass\/pricing\/"
    ],
    [
        "aws_iot",
        "AWS IoT",
        "https:\/\/console.aws.amazon.com\/iot\/home",
        "https:\/\/aws.amazon.com\/iot-platform\/pricing\/"
    ],
    [
        "appstream_2.0",
        "AppStream 2.0",
        "https:\/\/console.aws.amazon.com\/appstream2\/home",
        "https:\/\/aws.amazon.com\/appstream2\/pricing\/"
    ],
    [
        "application_discovery_service",
        "Application Discovery Service",
        "https:\/\/console.aws.amazon.com\/discovery\/home",
        ""
    ],
    [
        "artifact",
        "Artifact",
        "https:\/\/console.aws.amazon.com\/artifact\/home",
        ""
    ],
    [
        "athena",
        "Athena",
        "https:\/\/console.aws.amazon.com\/athena\/home",
        "https:\/\/aws.amazon.com\/athena\/pricing\/"
    ],
    [
        "batch",
        "Batch",
        "https:\/\/console.aws.amazon.com\/batch\/home",
        "https:\/\/aws.amazon.com\/batch\/pricing\/"
    ],
    [
        "certificate_manager",
        "Certificate Manager",
        "https:\/\/console.aws.amazon.com\/acm\/home",
        "https:\/\/aws.amazon.com\/certificate-manager\/pricing\/"
    ],
    [
        "amazon_chime",
        "Chime",
        "https:\/\/chime.aws.amazon.com",
        ""
    ],
    [
        "cloudformation",
        "CloudFormation",
        "https:\/\/console.aws.amazon.com\/cloudformation\/home",
        "https:\/\/aws.amazon.com\/cloudformation\/pricing\/"
    ],
    [
        "cloudfront",
        "CloudFront",
        "https:\/\/console.aws.amazon.com\/cloudfront\/home",
        "https:\/\/aws.amazon.com\/cloudfront\/pricing\/"
    ],
    [
        "cloudsearch",
        "CloudSearch",
        "https:\/\/console.aws.amazon.com\/cloudsearch\/home",
        "https:\/\/aws.amazon.com\/cloudsearch\/pricing\/"
    ],
    [
        "cloudtrail",
        "CloudTrail",
        "https:\/\/console.aws.amazon.com\/cloudtrail\/home",
        "https:\/\/aws.amazon.com\/cloudtrail\/pricing\/"
    ],
    [
        "cloudwatch",
        "CloudWatch",
        "https:\/\/console.aws.amazon.com\/cloudwatch\/home",
        "https:\/\/aws.amazon.com\/cloudwatch\/pricing\/"
    ],
    [
        "cloudwatch_events_rules",
        "Cloudwatch \/ Events \/ Rules",
        "https:\/\/console.aws.amazon.com\/cloudwatch\/home#rules:",
        ""
    ],
    [
        "cloudwatch_logs",
        "Cloudwatch \/ Logs",
        "https:\/\/console.aws.amazon.com\/cloudwatch\/home#logs:",
        ""
    ],
    [
        "cloudwatch_metrics",
        "Cloudwatch \/ Metrics",
        "https:\/\/console.aws.amazon.com\/cloudwatch\/home#metricsV2:",
        ""
    ],
    [
        "codebuild",
        "CodeBuild",
        "https:\/\/console.aws.amazon.com\/codebuild\/home",
        "https:\/\/aws.amazon.com\/codebuild\/pricing\/"
    ],
    [
        "codecommit",
        "CodeCommit",
        "https:\/\/console.aws.amazon.com\/codecommit\/home",
        "https:\/\/aws.amazon.com\/codecommit\/pricing\/"
    ],
    [
        "codedeploy",
        "CodeDeploy",
        "https:\/\/console.aws.amazon.com\/codedeploy\/home",
        "https:\/\/aws.amazon.com\/codedeploy\/pricing\/"
    ],
    [
        "codepipeline",
        "CodePipeline",
        "https:\/\/console.aws.amazon.com\/codepipeline\/home",
        "https:\/\/aws.amazon.com\/codepipeline\/pricing\/"
    ],
    [
        "codestar",
        "CodeStar",
        "https:\/\/console.aws.amazon.com\/codestar\/home",
        ""
    ],
    [
        "cognito",
        "Cognito",
        "https:\/\/console.aws.amazon.com\/cognito\/home",
        "https:\/\/aws.amazon.com\/cognito\/pricing\/"
    ],
    [
        "config",
        "Config",
        "https:\/\/console.aws.amazon.com\/config\/home",
        "https:\/\/aws.amazon.com\/config\/pricing\/"
    ],
    [
        "amazon_connect",
        "Connect",
        "https:\/\/console.aws.amazon.com\/connect\/home",
        ""
    ],
    [
        "dms",
        "DMS",
        "https:\/\/console.aws.amazon.com\/dms\/home",
        "https:\/\/aws.amazon.com\/dms\/pricing\/"
    ],
    [
        "data_pipeline",
        "Data Pipeline",
        "https:\/\/console.aws.amazon.com\/datapipeline\/home",
        "https:\/\/aws.amazon.com\/datapipeline\/pricing\/"
    ],
    [
        "device_farm",
        "Device Farm",
        "https:\/\/console.aws.amazon.com\/devicefarm\/home",
        "https:\/\/aws.amazon.com\/device-farm\/pricing\/"
    ],
    [
        "direct_connect",
        "Direct Connect",
        "https:\/\/console.aws.amazon.com\/directconnect\/home",
        "https:\/\/aws.amazon.com\/directconnect\/pricing\/"
    ],
    [
        "directory_service",
        "Directory Service",
        "https:\/\/console.aws.amazon.com\/directoryservice\/home",
        "https:\/\/aws.amazon.com\/directoryservice\/pricing\/"
    ],
    [
        "dynamodb",
        "DynamoDB",
        "https:\/\/console.aws.amazon.com\/dynamodb\/home",
        "https:\/\/aws.amazon.com\/dynamodb\/pricing\/"
    ],
    [
        "dynamodb_tables",
        "DynamoDB \/ Tables",
        "https:\/\/console.aws.amazon.com\/dynamodb\/home#tables:",
        ""
    ],
    [
        "ec2",
        "EC2",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home",
        "https:\/\/aws.amazon.com\/ec2\/pricing\/"
    ],
    [
        "ec2_amis",
        "EC2 \/ AMIs",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home#Images:sort=desc:creationDate",
        ""
    ],
    [
        "ec2_auto_scaling_groups",
        "EC2 \/ Auto Scaling Groups",
        "https:\/\/console.aws.amazon.com\/ec2\/autoscaling\/home#AutoScalingGroups:",
        ""
    ],
    [
        "ec2_ebs",
        "EC2 \/ EBS",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home#Volumes:",
        "https:\/\/aws.amazon.com\/ebs\/pricing\/"
    ],
    [
        "ec2_elb",
        "EC2 \/ ELB",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home#LoadBalancers:",
        "https:\/\/aws.amazon.com\/elasticloadbalancing\/pricing\/"
    ],
    [
        "ec2_instances",
        "EC2 \/ Instances",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home#Instances:",
        ""
    ],
    [
        "ec2_security_groups",
        "EC2 \/ Security Groups",
        "https:\/\/console.aws.amazon.com\/ec2\/v2\/home#SecurityGroups:",
        ""
    ],
    [
        "ec2_container_service",
        "EC2 Container Service",
        "https:\/\/console.aws.amazon.com\/ecs\/home",
        "https:\/\/aws.amazon.com\/ecs\/pricing\/"
    ],
    [
        "efs",
        "EFS",
        "https:\/\/console.aws.amazon.com\/efs\/home",
        "https:\/\/aws.amazon.com\/efs\/pricing\/"
    ],
    [
        "emr",
        "EMR",
        "https:\/\/console.aws.amazon.com\/elasticmapreduce\/home",
        "https:\/\/aws.amazon.com\/emr\/pricing\/"
    ],
    [
        "elasticache",
        "ElastiCache",
        "https:\/\/console.aws.amazon.com\/elasticache\/home",
        "https:\/\/aws.amazon.com\/elasticache\/pricing\/"
    ],
    [
        "elasticache_memcached",
        "ElastiCache \/ Memcached",
        "https:\/\/console.aws.amazon.com\/elasticache\/home#memcached:",
        ""
    ],
    [
        "elasticache_redis",
        "ElastiCache \/ Redis",
        "https:\/\/console.aws.amazon.com\/elasticache\/home#redis:",
        ""
    ],
    [
        "elastic_beanstalk",
        "Elastic Beanstalk",
        "https:\/\/console.aws.amazon.com\/elasticbeanstalk\/home",
        "https:\/\/aws.amazon.com\/elasticbeanstalk\/pricing\/"
    ],
    [
        "elastic_transcoder",
        "Elastic Transcoder",
        "https:\/\/console.aws.amazon.com\/elastictranscoder\/home",
        "https:\/\/aws.amazon.com\/elastictranscoder\/pricing\/"
    ],
    [
        "elasticsearch_service",
        "Elasticsearch Service",
        "https:\/\/console.aws.amazon.com\/es\/home",
        "https:\/\/aws.amazon.com\/elasticsearch-service\/pricing\/"
    ],
    [
        "amazon_gamelift",
        "GameLift",
        "https:\/\/console.aws.amazon.com\/gamelift\/home",
        ""
    ],
    [
        "glacier",
        "Glacier",
        "https:\/\/console.aws.amazon.com\/glacier\/home",
        "https:\/\/aws.amazon.com\/glacier\/pricing\/"
    ],
    [
        "iam",
        "IAM",
        "https:\/\/console.aws.amazon.com\/iam\/home",
        ""
    ],
    [
        "inspector",
        "Inspector",
        "https:\/\/console.aws.amazon.com\/inspector\/home",
        "https:\/\/aws.amazon.com\/inspector\/pricing\/"
    ],
    [
        "kinesis",
        "Kinesis",
        "https:\/\/console.aws.amazon.com\/kinesis\/home",
        "https:\/\/aws.amazon.com\/kinesis\/streams\/pricing\/"
    ],
    [
        "lambda",
        "Lambda",
        "https:\/\/console.aws.amazon.com\/lambda\/home",
        "https:\/\/aws.amazon.com\/lambda\/pricing\/"
    ],
    [
        "lex",
        "Lex",
        "https:\/\/console.aws.amazon.com\/lex\/home",
        "https:\/\/aws.amazon.com\/lex\/pricing\/"
    ],
    [
        "lightsail",
        "Lightsail",
        "https:\/\/lightsail.aws.amazon.com\/ls\/webapp\/home",
        "https:\/\/amazonlightsail.com\/pricing\/"
    ],
    [
        "machine_learning",
        "Machine Learning",
        "https:\/\/console.aws.amazon.com\/machinelearning\/home",
        "https:\/\/aws.amazon.com\/machine-learning\/pricing\/"
    ],
    [
        "managed_services",
        "Managed Services",
        "https:\/\/console.aws.amazon.com\/managedservices\/home",
        ""
    ],
    [
        "mobile_analytics",
        "Mobile Analytics",
        "https:\/\/console.aws.amazon.com\/mobileanalytics\/home",
        "https:\/\/aws.amazon.com\/mobileanalytics\/pricing\/"
    ],
    [
        "mobile_hub",
        "Mobile Hub",
        "https:\/\/console.aws.amazon.com\/mobilehub\/home",
        "https:\/\/aws.amazon.com\/mobile\/pricing\/"
    ],
    [
        "opsworks",
        "OpsWorks",
        "https:\/\/console.aws.amazon.com\/opsworks\/landing\/home",
        "https:\/\/aws.amazon.com\/opsworks\/pricing\/"
    ],
    [
        "pinpoint",
        "Pinpoint",
        "https:\/\/console.aws.amazon.com\/pinpoint\/home",
        "https:\/\/aws.amazon.com\/pinpoint\/pricing\/"
    ],
    [
        "polly",
        "Polly",
        "https:\/\/console.aws.amazon.com\/polly\/home",
        "https:\/\/aws.amazon.com\/polly\/pricing\/"
    ],
    [
        "quicksight",
        "QuickSight",
        "https:\/\/quicksight.aws.amazon.com",
        "https:\/\/aws.amazon.com\/quicksight\/pricing\/"
    ],
    [
        "rds",
        "RDS",
        "https:\/\/console.aws.amazon.com\/rds\/home",
        "https:\/\/aws.amazon.com\/rds\/pricing\/"
    ],
    [
        "rds_clusters",
        "RDS \/ Clusters",
        "https:\/\/console.aws.amazon.com\/rds\/home#dbclusters:",
        ""
    ],
    [
        "rds_instances",
        "RDS \/ Instances",
        "https:\/\/console.aws.amazon.com\/rds\/home#dbinstances:",
        ""
    ],
    [
        "redshift",
        "Redshift",
        "https:\/\/console.aws.amazon.com\/redshift\/home",
        "https:\/\/aws.amazon.com\/redshift\/pricing\/"
    ],
    [
        "rekognition",
        "Rekognition",
        "https:\/\/console.aws.amazon.com\/rekognition\/home",
        "https:\/\/aws.amazon.com\/rekognition\/pricing\/"
    ],
    [
        "route_53",
        "Route 53",
        "https:\/\/console.aws.amazon.com\/route53\/home",
        "https:\/\/aws.amazon.com\/route53\/pricing\/"
    ],
    [
        "route53_hosted_zones",
        "Route 53 \/ Hosted Zones",
        "https:\/\/console.aws.amazon.com\/route53\/home?#hosted-zones:",
        ""
    ],
    [
        "s3",
        "S3",
        "https:\/\/console.aws.amazon.com\/s3\/home",
        "https:\/\/aws.amazon.com\/s3\/pricing\/"
    ],
    [
        "ses",
        "SES",
        "https:\/\/console.aws.amazon.com\/ses\/home",
        "https:\/\/aws.amazon.com\/ses\/pricing\/"
    ],
    [
        "ses_domains",
        "SES \/ Domains",
        "https:\/\/console.aws.amazon.com\/ses\/home#verified-senders-domain:",
        ""
    ],
    [
        "swf",
        "SWF",
        "https:\/\/console.aws.amazon.com\/swf\/home",
        ""
    ],
    [
        "server_migration",
        "Server Migration",
        "https:\/\/console.aws.amazon.com\/servermigration\/home",
        ""
    ],
    [
        "service_catalog",
        "Service Catalog",
        "https:\/\/console.aws.amazon.com\/catalog\/home",
        "https:\/\/aws.amazon.com\/servicecatalog\/pricing\/"
    ],
    [
        "simple_notification_service",
        "Simple Notification Service",
        "https:\/\/console.aws.amazon.com\/sns\/home",
        "https:\/\/aws.amazon.com\/sns\/pricing\/"
    ],
    [
        "simple_queue_service",
        "Simple Queue Service",
        "https:\/\/console.aws.amazon.com\/sqs\/home",
        "https:\/\/aws.amazon.com\/sqs\/pricing\/"
    ],
    [
        "snowball",
        "Snowball",
        "https:\/\/console.aws.amazon.com\/importexport\/home",
        "https:\/\/aws.amazon.com\/snowball\/pricing\/"
    ],
    [
        "step_functions",
        "Step Functions",
        "https:\/\/console.aws.amazon.com\/states\/home",
        "https:\/\/aws.amazon.com\/step-functions\/pricing\/"
    ],
    [
        "storage_gateway",
        "Storage Gateway",
        "https:\/\/console.aws.amazon.com\/storagegateway\/home",
        "https:\/\/aws.amazon.com\/storagegateway\/pricing\/"
    ],
    [
        "trusted_advisor",
        "Trusted Advisor",
        "https:\/\/console.aws.amazon.com\/trustedadvisor\/home",
        "https:\/\/aws.amazon.com\/premiumsupport\/trustedadvisor\/"
    ],
    [
        "vpc",
        "VPC",
        "https:\/\/console.aws.amazon.com\/vpc\/home",
        "https:\/\/aws.amazon.com\/vpc\/pricing\/"
    ],
    [
        "waf_&_shield",
        "WAF & Shield",
        "https:\/\/console.aws.amazon.com\/waf\/home",
        "https:\/\/aws.amazon.com\/waf\/pricing\/"
    ],
    [
        "workdocs",
        "WorkDocs",
        "https:\/\/console.aws.amazon.com\/zocalo\/home",
        "https:\/\/aws.amazon.com\/workdocs\/pricing\/"
    ],
    [
        "workmail",
        "WorkMail",
        "https:\/\/console.aws.amazon.com\/workmail\/home",
        "https:\/\/aws.amazon.com\/workmail\/"
    ],
    [
        "workspaces",
        "WorkSpaces",
        "https:\/\/console.aws.amazon.com\/workspaces\/home",
        "https:\/\/aws.amazon.com\/workspaces\/pricing\/"
    ],
    [
        "x-ray",
        "X-Ray",
        "https:\/\/console.aws.amazon.com\/xray\/home",
        "https:\/\/aws.amazon.com\/xray\/pricing\/"
    ]
];
